//GENERATED BY WOLFETPLAYER - 05-09-19 for
//https://www.moddb.com/mods/realrtcw-realism-mod




// SNOOPER

models/weapons2/garand/rifle2
{
	{
		map textures/effects/envmap_slateH2.tga
		rgbGen lightingDiffuse
		tcMod scale 1.5 1.5
		tcGen environment 
	}
	{
		map models/weapons2/garand/rifle2.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
	{
		map textures/dtx/ametal2.tga
		blendfunc filter
		rgbGen identity
		tcMod scale 6 6
		detail
	}
	{
		map models/weapons2/garand/rifle2_glow.tga
		blendfunc add
		rgbGen wave sawtooth 0.8 0.1 0 8 
	}
}


// TESLA

// TESLA

models/weapons2/tesla/base_tesla4
{
	{
		map textures/effects/metal_new.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/weapons2/tesla/base_tesla4.tga
		blendfunc filter
		rgbGen lightingDiffuse
	}
	{
		map models/weapons2/tesla/glow1.tga
		blendfunc add
		rgbGen wave triangle 0.5 0.4 0 0.8 
	}
	{
		map models/weapons2/tesla/glow2.tga
		blendfunc add
		rgbGen wave triangle 0.5 1 0 1 
	}
	{
		map models/weapons2/tesla/base_tesla4_glow.tga
		blendfunc add
		rgbGen wave triangle 0.5 0.5 0 0.5 
	}
}



models/powerups/ammo/amtesla
{
	{
		map textures/effects/specularB.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/powerups/ammo/amtesla.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}

models/multiplayer/supplies/ammobox
{
	{
		map textures/effects/envmap_slate.tga
		rgbGen lightingDiffuse
		tcGen environment 
	}
	{
		map models/multiplayer/supplies/ammobox.tga
		blendfunc blend
		rgbGen lightingDiffuse
	}
}




